### PR TITLE
Page height fix, responsive menu

### LINKED ISSUE #849: New design should fill the page...
... even if it is too short to actually do so.

### PR DESCRIPTION
**Pull request by andymikulski**
~Depends on PR #847~

- Fixes #849 - makes page stretch to fill window
- Adds responsive navigation menu so site looks better on mobile

screen shot 2017-06-28 at 5 00 59 pm

### CODE REVIEW

**Comment by rehandalal** [comment]
this needs a rebase and a merge conflict fix.

**Comment by andymikulski** [comment]
@rehandalal This is all set - not sure if you want to check it out before merging.

File: recipe-server/client/control_new/components/App.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { Layout, LocaleProvider } from 'antd';
 import enUS from 'antd/lib/locale-provider/en_US';
 import PropTypes from 'prop-types';
 import React from 'react';
+import {Link} from 'redux-little-router';
```
Comment (rehandalal) [inline recipe-server/client/control_new/components/App.js]: Linter will complain about this not being:
`{ Link }`
