### PR TITLE
#1054, #1055: Prevent dupe recipes in recent history

### LINKED ISSUE #1054: Duplicate recipes in sidebar.
One link goes to the `/recipe/{id}` page and the other goes to `/recipe/{id}/edit`.

screenshot-2017-9-7 shield control panel

### LINKED ISSUE #1055: Duplicate key error.
Error:
> Warning: flattenChildren(...): Encountered two children with the same key, \`.2:$/recipe/20/edit\`. [...]

This is probably an issue with `NavigationMenu.js`, specifically `recipeSessionHistory`.

### PR DESCRIPTION
**Pull request by andymikulski**
- Fixes #1054  - duplicate recipes in sidebar
- Fixes #1055 - duplicate React key warning

- ~Adds a check to snip `/edit`, `/clone`, and `/approval_request` from 'session views', ensuring that links in the 'recent recipes' section are to the `view recipe` page and never `edit recipe`, etc.~ 
Adds `slug` and `sessionSlug` properties to routes. If a route has a `sessionSlug`, that is the path used for session purposes (i.e. recently viewed nav list).
- Adds `getNamedPath` router util, which returns a URL given an internal route slug
- Adds shield identicons to menu nav since they were not implemented when landed
- Adds tests

Ready for review!

### CODE REVIEW

File: recipe-server/client/control/state/app/session/actions.js [hunk 1]
```diff
@@ -61,13 +61,17 @@ export function saveSession() {
...
 
-export function addSessionView(category, caption) {
+export function addSessionView(category, caption, identicon) {
   return async (dispatch, getState) => {
-    const url = getState().router.pathname;
+    let url = getState().router.pathname;
+
+    // Prevent exact subpages (e.g. edit, clone pages) from appearing in the nav.
+    // Instead, this will link to the 'view' page for that recipe/revision.
+    url = url.replace(/\/(edit|clone|approval_history)/, '');
```
Comment (mythmon) [inline recipe-server/client/control/state/app/session/actions.js]: This seems fragile. It requires this function to know about all the rest of the code, and makes it less re-usable. I think this should be refactored so that callers pass the URL. That way each individual caller can manager how it's URLs need to be deduplicated.

Either that, or this sort of "parent page" information should be stored on the route, so it is stored in a central place with the routing information.

File: recipe-server/client/control/tests/state/session/test_actions.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+    const defaultParams = ['category', 'caption', 'identicon'];
+    // Values = the 'default' dispatched values given our default params.
+    const defaultValues = { caption: 'caption', category: 'category', identicon: 'identicon' };
+
+
+    it('should dispatch a SESSION_INFO_HISTORY_VIEW event', async () => {
+      const meta = {
+        dispatch: () => {},
+      };
+      spyOn(meta, 'dispatch').and.callThrough();
```
Comment (mythmon) [inline recipe-server/client/control/tests/state/session/test_actions.js]: You can probably do this more cleanly with [`jasmine.createSpy`](https://jasmine.github.io/2.0/introduction.html#section-Spies:_%3Ccode%3EcreateSpy%3C/code%3E):

File: recipe-server/client/control/state/app/session/actions.js (hunk 1 above)
Comment (andymikulski) [reply recipe-server/client/control/state/app/session/actions.js]: I've gone with a bit of a combination of both options, seen in the latest commit: https://github.com/mozilla/normandy/pull/1076/commits/514f3359fbc23074975e6f28ed61baa1d2924604 

On the route definitions, I use an `ignoreSession` variable to determine if it should handle changing the reported URL. Then, in order to know what the 'correct' URL is, I put together a `getNamedRoute` function which traverses the route tree and finds the specified path based on the given crumb. For example:

```
getNamedRoute('New Extension') === '/extension/new/'
getNamedRoute('View Recipe') === '/recipe/:recipeId/'
getNamedRoute('View Recipe', { recipeId: 3 }) === '/recipe/3/'
```

This `getNamedRoute` function will actually be useful in a few places, so I quite like this approach. I still have to write tests, but this code/commit is certainly open for feedback.

File: recipe-server/client/control/state/app/session/actions.js [hunk 3]
```diff
@@ -61,13 +62,23 @@ export function saveSession() {
...
   return async (dispatch, getState) => {
-    const url = getState().router.pathname;
+    const { router } = getState();
+    let url = router.pathname;
+    const ignoreSession = router.result && router.result.ignoreSession;
+
+    // Prevent exact subpages (e.g. edit, clone pages) from appearing in the nav.
+    // Instead, this will link to the proper 'View [Recipe|Extension]' page.
+    if (ignoreSession) {
+      url = getNamedRoute(`View ${capitalize(category)}`, router.params);
```
Comment (mythmon) [inline recipe-server/client/control/state/app/session/actions.js]: I don't think that using user-facing names for url routing is a good idea. I think that routes should have another field (maybe slug?) that we can use for specifying routes. Specifically, needing to call capitalize seems like a bad thing here. It makes form and function too closely linked.

File: recipe-server/client/control/routes.js [hunk 4]
```diff
@@ -42,30 +42,35 @@ const routes = {
           '/': {
             component: RecipeDetailPage,
             crumb: 'Revision',
+            ignoreSession: true,
```
Comment (mythmon) [inline recipe-server/client/control/routes.js]: Can you explain the choice of name `ignoreSession`? I don't think I get it.

It might also be good to have a comment above the routes explaining the extra keys we are adding. They all make sense now, but they aren't documented anywhere, and the schema is pretty important.

Comment (andymikulski) [reply recipe-server/client/control/routes.js]: The idea behind `ignoreSession` was to ignore the route for session purposes, but I agree it is/was too vague. I've switched over to this format:

```
...
'/clone': {
  '/': {
    component: CloneRecipePage,
    crumb: 'Clone Recipe',
    sessionSlug: 'recipe-view',
    slug: 'recipe-clone',
  },
},
...
```

With this approach, we can simply point to another slug and anything session-related will use that over the actual `slug`. This feels a bit better since the `routes.js` file now lets us define the redirect behavior without having to tie directly into the underlying breadcrumb/current URL stuff.

File: recipe-server/client/control/state/app/session/actions.js (hunk 3 above)
Comment (andymikulski) [reply recipe-server/client/control/state/app/session/actions.js]: Using `slug`s has changed this to ```url = getNamedRoute(`${category}-view`);```, good idea!

**Comment by andymikulski** [comment]
This now utilizes `slug`s, `sessionSlug`s, and has all the appropriate tests. This should be ready for a final pass!

File: recipe-server/client/control/routerUtils.js [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+  // If we have the slug, we have the complete route.
+  if (tree.slug === name) {
+    return currentUrl;
+  }
+
+  // If the slug doesn't match, iterate over the given route tree until
+  // we find one that matches what we need (if any exist).
+  const keys = Object.keys(tree);
+  for (let i = 0; i < keys.length; i += 1) {
+    const curPath = keys[i];
```
Comment (mythmon) [inline recipe-server/client/control/routerUtils.js]: Nit: I think this could be done as `for (const curPath of Object.keys(tree)) {`,

**Comment by andymikulski** [comment]
Merging once CI is happy!
