### PR TITLE
Fix #824: Run add-on tests using mochitest/xpcshell-test directly.

### LINKED ISSUE #824: ./mach test on the xpcshell tests fails, but ./mach xpcshell-test doesn't
When run with the generic `./mach test` command, the xpcshell tests fail:

```sh
$ ./bin/update-mozilla-central.sh ~/Projects/mozilla-unified && ( workon mozilla-unified && ./mach test browser/extensions/shield-recipe-client/test/unit )
Build configuration changed. Regenerating backend.
 0:00.28 LOG: MainThread WARNING MOZ_NODE_PATH environment variable not set. Tests requiring http/2 will fail.
Error running mach:

    ['test', 'browser/extensions/shield-recipe-client/test/unit']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AttributeError: 'NoneType' object has no attribute 'startswith'

  File "/Users/mkelly/Projects/mozilla-unified/testing/mach_commands.py", line 343, in test
    test_objects=tests, **kwargs)
  File "/Users/mkelly/Projects/mozilla-unified/python/mach/mach/registrar.py", line 123, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/Users/mkelly/Projects/mozilla-unified/python/mach/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/mach_commands.py", line 269, in run_xpcshell_test
    return xpcshell.run_test(**params)
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/mach_commands.py", line 61, in run_test
    return self.run_suite(**kwargs)
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/mach_commands.py", line 47, in run_suite
    return self._run_xpcshell_harness(**kwargs)
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/mach_commands.py", line 137, in _run_xpcshell_harness
    result = xpcshell.runTests(**filtered_args)
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/runxpcshelltests.py", line 1274, in runTests
    self.buildTestList(test_tags, testPaths)
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/runxpcshelltests.py", line 874, in buildTestList
    self.alltests = map(normalize, mp.active_tests(filters=filters, **mozinfo.info))
  File "/Users/mkelly/Projects/mozilla-unified/testing/xpcshell/runxpcshelltests.py", line 837, in normalizeTest
    test_object['manifest'] = os.path.relpath(test_object['manifest'], root)
  File "/Users/mkelly/.virtualenvs/mozilla-unified/lib/python2.7/posixpath.py", line 430, in relpath
    start_list = [x for x in abspath(start).split(sep) if x]
  File "/Users/mkelly/.virtualenvs/mozilla-unified/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/mkelly/.virtualenvs/mozilla-unified/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
```

If you try to run them with `./mach xpcshell-test`, they run and pass without an issue.

### PR DESCRIPTION
**Pull request by Osmose**

### CODE REVIEW

File: recipe-client-addon/bin/tc/build_test.sh [hunk 1]
```diff
@@ -31,8 +31,11 @@ echo 'ac_add_options --enable-artifact-builds' > ./mozconfig
 mkdir /root/.mozbuild  # Otherwise mach will hang forever asking for permission
 ./mach build
 
-echo 'Running tests'
-xvfb-run ./mach test browser/extensions/shield-recipe-client/
+echo 'Running mochitests'
+xvfb-run ./mach mochitest browser/extensions/shield-recipe-client/browser
```
Comment (mythmon) [inline recipe-client-addon/bin/tc/build_test.sh]: I don't  think this is the right path. I think you want `.../shield-recipe-client/test/browser`, and similar for `unit` below.

Comment (Osmose) [inline recipe-client-addon/bin/tc/build_test.sh]: Whoops
