### PR TITLE
#910: Fix broken approvals (new UI)

### LINKED ISSUE #910: Can't approve a recipe
Steps to reproduce:

1. Click  'new recipe'
2. Fill out 'create new recipe' form
3. Click 'save' button
4. Click 'request approval'
5. Click 'approval request'
6. Click 'approve' 
At this point, the approve button doesn't seem to any effect and I can't self-approve a recipe that I created.

### PR DESCRIPTION
**Pull request by andymikulski**
Fixes #910 

- Fixes `approvalApprovalRequest` typo (preventing approvals from working at all)
- Fixes `error.data.error` issues (error reported in #910)
- Changed the `LoadingOverlay`s in `ApprovalForm/Request` to not affect the approval form upon submission
  - Previously, any `comment` text would be wiped out due to the `LoadingOverlay` flipping the dom.

Ready for review. I've tagged @rehandalal and @mythmon , I reckon whoever gets to it first should be fine.

### CODE REVIEW

File: recipe-server/client/control_new/components/recipes/ApprovalRequest.js [hunk 1]
```diff
@@ -154,3 +143,32 @@ export default class ApprovalRequest extends React.Component {
     );
   }
 }
+
+class RequestDetails extends React.PureComponent {
```
Comment (rehandalal) [inline recipe-server/client/control_new/components/recipes/ApprovalRequest.js]: this should probably go in it's own file if we're making it a component.

**Comment by andymikulski** [comment]
@rehandalal I've split out the component into its own file `ApprovalDetails`
