### PR TITLE
Fix #823: Properly wait for test webextension to startup.

### LINKED ISSUE #823: Mochitest failure: data["Extension:Extensions"] is undefined
Running the mochitests locally (and in automation) has the following test failure:

```
438 INFO TEST-UNEXPECTED-FAIL | browser/extensions/shield-recipe-client/test/browser/browser_NormandyDriver.js | A promise chain failed to handle a rejection: data['Extension:Extensions'] is undefined - rejection date: Wed Jun 21 2017 12:50:57 GMT-0700 (PDT) - stack: null - false == true - JS frame :: resource://testing-common/PromiseTestUtils.jsm :: assertNoUncaughtRejections :: line 257
Stack trace:
    resource://testing-common/PromiseTestUtils.jsm:assertNoUncaughtRejections:257
    chrome://mochikit/content/browser-test.js:Tester_execTest/<:801
    Tester_execTest@chrome://mochikit/content/browser-test.js:774:9
    Tester.prototype.nextTest</<@chrome://mochikit/content/browser-test.js:686:7
    SimpleTest.waitForFocus/waitForFocusInner/focusedOrLoaded/<@chrome://mochikit/content/tests/SimpleTest/SimpleTest.js:795:59
```

### PR DESCRIPTION
**Pull request by Osmose**
The tests for installing and uninstalling an add-on use a webextension,
and if we uninstall the add-on before it finishes starting up, the
async startup process throws an error.

### CODE REVIEW

File: recipe-client-addon/test/browser/browser_NormandyDriver.js [hunk 1]
```diff
@@ -22,10 +23,8 @@ add_task(withDriver(Assert, async function installXpi(driver) {
   is(addonId, "normandydriver@example.com", "Expected test addon was installed");
   isnot(addonId, null, "Addon install was successful");
 
-  // Installing kicks off an asychronous process which tries to read the manifest.json
-  // to startup the addon. Note that onInstallEnded is triggered too early
-  // which is why we need this delay.
-  await new Promise(resolve => SimpleTest.executeSoon(resolve));
+  // Wait until the add-on is fully started up to uninstall it.
+  await AddonTestUtils.promiseWebExtensionStartup("normandydriver@example.com");
```
Comment (kmaglione) [inline recipe-client-addon/test/browser/browser_NormandyDriver.js]: It's best to create the promise before you install/start the extension, so you don't risk adding the startup listener after startup is complete.

**Comment by Osmose** [comment]
TC failure is #824. The failure this is aiming to fix no longer appears in the logs, so I'm considering it a success.
